<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="API\Domain\Enum\**" />
    <Compile Remove="API\Domain\Exception\**" />
    <Compile Remove="Controllers\**" />
    <Content Remove="API\Domain\Enum\**" />
    <Content Remove="API\Domain\Exception\**" />
    <Content Remove="Controllers\**" />
    <EmbeddedResource Remove="API\Domain\Enum\**" />
    <EmbeddedResource Remove="API\Domain\Exception\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="API\Domain\Enum\**" />
    <None Remove="API\Domain\Exception\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="API\Data\Configuration\" />
    <Folder Include="API\Domain\Common\" />
    <Folder Include="API\Domain\Entity\" />
    <Folder Include="API\Domain\Policy\" />
    <Folder Include="API\DTO\" />
    <Folder Include="API\Mapping\" />
    <Folder Include="API\Middleware\" />
    <Folder Include="API\Service\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
